# Generated by Django 3.0.2 on 2020-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0012_auto_20200226_1548'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_licks',
            field=models.ManyToManyField(blank=True, related_name='liked_licks', to='repo.Lick'),
        ),
    ]
