# Generated by Django 3.0.5 on 2020-07-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instr_transpose_shift',
            field=models.CharField(choices=[('concert', '0'), ('Eb', '-3'), ('Bb', '2')], default='0', max_length=10),
        ),
    ]
