# Generated by Django 3.0.5 on 2020-07-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_instr_transpose_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instr_transpose_shift',
            field=models.CharField(choices=[('0', 'concert'), ('-3', 'Eb'), ('2', 'Bb')], default='concert', max_length=10),
        ),
    ]
