# Generated by Django 3.0.5 on 2020-06-30 19:39

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0006_auto_20200508_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter a blog post category', max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=280)),
                ('body', models.TextField(max_length=50000)),
                ('image', models.ImageField(blank=True, height_field='height_field', upload_to=blog.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('date_published', models.DateField(verbose_name='date published')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('lick_string', models.CharField(blank=True, max_length=50, null=True)),
                ('transpose_string', models.CharField(blank=True, max_length=50, null=True)),
                ('lick_placeholders_string', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('licks', models.ManyToManyField(blank=True, to='repo.Lick')),
            ],
        ),
    ]
