# Generated by Django 3.0.5 on 2020-06-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20200508_0021'),
        ('blog', '0002_auto_20200520_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='licks',
            field=models.ManyToManyField(blank=True, to='repo.Lick'),
        ),
    ]
