# Generated by Django 3.0.5 on 2020-06-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_licks'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lick_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='transpose_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
