# Generated by Django 3.0.5 on 2020-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200610_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lick_placeholders_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
