# Generated by Django 3.0.5 on 2020-07-26 02:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200704_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='thumb_height_field', upload_to=blog.models.upload_location, width_field='thumb_width_field'),
        ),
    ]
