# Generated by Django 3.0.5 on 2020-05-11 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200510_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=280),
            preserve_default=False,
        ),
    ]
