# Generated by Django 3.0.5 on 2020-07-26 02:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200726_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, height_field='thumb_height_field', upload_to=blog.models.upload_location, width_field='thumb_width_field'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', upload_to=blog.models.upload_location, width_field='width_field'),
        ),
    ]
