# Generated by Django 3.0.5 on 2020-07-26 03:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200726_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=blog.models.upload_location),
        ),
    ]
