# Generated by Django 2.2.6 on 2020-01-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lick',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
