# Generated by Django 2.2.6 on 2020-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20200102_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='lick',
            name='key',
            field=models.CharField(choices=[('F', 'F'), ('Fm', 'Fm'), ('C', 'C'), ('Cm', 'Cm'), ('Bb', 'Bb')], default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='lick',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
