# Generated by Django 2.2.3 on 2020-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_chords_chord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chords',
        ),
        migrations.AddField(
            model_name='lick',
            name='chord_seq',
            field=models.CharField(default='-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-', max_length=100),
        ),
    ]
