# Generated by Django 3.0.5 on 2020-04-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0003_lick_chord_seq_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lick',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lick',
            name='chord_seq',
            field=models.CharField(default='x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x', max_length=150),
        ),
        migrations.AlterField(
            model_name='lick',
            name='chord_seq_search',
            field=models.CharField(default='x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x', max_length=150),
        ),
    ]
