# Generated by Django 3.0.5 on 2020-04-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20200412_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lick',
            name='chord_seq',
            field=models.CharField(default='xdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashx', max_length=150),
        ),
        migrations.AlterField(
            model_name='lick',
            name='chord_seq_search',
            field=models.CharField(default='xdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashxdashx', max_length=150),
        ),
    ]
