# Generated by Django 2.2.6 on 2020-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20200111_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lick',
            name='key',
            field=models.CharField(choices=[('-', '-'), (('F', 'F'), (('6', '6'), ('7', '7'))), ('Fm', 'Fm'), ('C', 'C'), ('Cm', 'Cm'), ('Bb', 'Bb')], default='-', max_length=4),
        ),
    ]
