# Generated by Django 2.2.3 on 2020-02-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20200201_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lick',
            name='chord_seq',
        ),
    ]
