# Generated by Django 3.0.5 on 2020-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20200423_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lick',
            name='chord_seq',
            field=models.CharField(default='x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x', max_length=150),
        ),
        migrations.AlterField(
            model_name='lick',
            name='chord_seq_search',
            field=models.CharField(default='x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x', max_length=150),
        ),
    ]
