# Generated by Django 2.2.6 on 2020-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20200111_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lick',
            name='key',
        ),
        migrations.AddField(
            model_name='lick',
            name='key1_1',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lick',
            name='key1_2',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lick',
            name='key1_3',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lick',
            name='key1_4',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
    ]
