# Generated by Django 2.2.3 on 2020-02-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_remove_lick_chord_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='lick',
            name='chord_seq',
            field=models.CharField(default='-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-', max_length=100),
        ),
    ]
