# Generated by Django 2.2.6 on 2020-01-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20200111_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an instrument (e.g. Piano, Guitar)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lick',
            name='key2_1',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lick',
            name='key2_2',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lick',
            name='key2_3',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lick',
            name='key2_4',
            field=models.CharField(choices=[('-', '-'), ('F', (('F', 'F'), ('Fm', 'Fm'), ('F7', 'F7'), ('Fm7', 'Fm7'), ('Fmaj7', 'Fmaj7'), ('F6', 'F6'), ('Fm7b5', 'Fm7b5'), ('F°', 'F°'))), ('E', (('E', 'E'), ('Em', 'Em'), ('E7', 'E7'), ('Em7', 'Em7'), ('Emaj7', 'Emaj7'), ('E6', 'E6'), ('Em7b5', 'Em7b5'), ('E°', 'E°'))), ('Eb', (('Eb', 'Eb'), ('Ebm', 'Ebm'), ('Eb7', 'Eb7'), ('Ebm7', 'Ebm7'), ('Ebmaj7', 'Ebmaj7'), ('Eb6', 'Eb6'), ('Ebm7b5', 'Ebm7b5'), ('Eb°', 'Eb°'))), ('D', (('D', 'D'), ('Dm', 'Dm'), ('D7', 'D7'), ('Dm7', 'Dm7'), ('Dmaj7', 'Dmaj7'), ('D6', 'D6'), ('Dm7b5', 'Dm7b5'), ('D°', 'D°')))], default='-', max_length=10),
        ),
    ]
