# Generated by Django 3.0.5 on 2020-08-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_lick_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lick',
            old_name='notes',
            new_name='description',
        ),
    ]
