# Generated by Django 2.2.6 on 2020-01-12 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_auto_20200111_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='lick',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='repo.Instrument'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(default='not specified', help_text='Enter an instrument (e.g. Piano, Guitar)', max_length=200),
        ),
    ]
