# Generated by Django 3.0.2 on 2020-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_auto_20200202_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lick',
            name='time_signature',
            field=models.CharField(choices=[('44', '4/4'), ('34', '3/4')], default='4/4', max_length=5),
        ),
    ]
