# Generated by Django 3.0.2 on 2020-02-24 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0009_auto_20200221_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='lick',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
