# Generated by Django 2.2.6 on 2020-01-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0011_auto_20200120_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='img/model_chords/')),
            ],
        ),
    ]
