# Generated by Django 3.0.2 on 2020-02-26 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0011_auto_20200225_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lick',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='lick',
            name='likes',
        ),
        migrations.AddField(
            model_name='lick',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
