# Generated by Django 3.0.1 on 2020-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0012_chords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chords',
        ),
        migrations.AddField(
            model_name='lick',
            name='time_signature',
            field=models.CharField(choices=[('4/4', '4/4'), ('3/4', '3/4')], default='4/4', max_length=5),
        ),
    ]
