# Generated by Django 3.0.2 on 2020-03-01 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0012_auto_20200226_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='lick',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
