# Generated by Django 3.0.1 on 2020-01-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0013_auto_20200121_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lick',
            old_name='beat1',
            new_name='m1_b1',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat10',
            new_name='m1_b2',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat11',
            new_name='m1_b3',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat12',
            new_name='m1_b4',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat13',
            new_name='m2_b1',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat14',
            new_name='m2_b2',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat15',
            new_name='m2_b3',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat16',
            new_name='m2_b4',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat2',
            new_name='m3_b1',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat3',
            new_name='m3_b2',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat4',
            new_name='m3_b3',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat5',
            new_name='m3_b4',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat6',
            new_name='m4_b1',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat7',
            new_name='m4_b2',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat8',
            new_name='m4_b3',
        ),
        migrations.RenameField(
            model_name='lick',
            old_name='beat9',
            new_name='m4_b4',
        ),
    ]
